#pragma config(Sensor, in2,    mogo,           sensorPotentiometer)
#pragma config(Sensor, in3,    g,              sensorGyro)
#pragma config(Sensor, dgtl1,  drive,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mogolift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           mogolift2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// SCROLL DOWN FOR INTRUCTIONS @MEGHAJ @MEGHAJ @MEGHAJ @MEGHAJ @MEGHAJ @MEGHAJ @MEGHAJ

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
// pid functions and such here, SCROLL DOWN UNTIL YOU SEE    task autonomous()
// green is comments so they dont affect code.
void mogoliftdown()
{
	while(SensorValue[port2] < 1235)
	{
		motor[port4] = -127;
		motor[port7] = -127;
	}
	motor[port4] = 0;
	motor[port7] = 0;
}
void mogoliftup()
{
	while(SensorValue[port2] > 175)
	{
		motor[port4] = 50;
		motor[port7] = 50;
	}
	motor[port4] = 0;
	motor[port7] = 0;
	wait10Msec(30);
}



void mogoliftbit()
{
	while(SensorValue[port2] < 200)
	{
		motor[port4] = -127;
		motor[port7] = -127;
	}
	motor[port4] = 0;
	motor[port7] = 0;
}
void turnpid(int gyroval)
{

	SensorValue[port3] = 0;
	float gkp = 0.55;
	float gerror;
	float kd = 0.085;
	float der = 0;
	if(gyroval == 90)
	{
		gkp = 0.64;
	}
	if(gyroval == 180)
	{
		gkp = 0.45;
	}
	bool checkr = false;
	while(checkr == false)
	{
		gerror = (gyroval * 10) - SensorValue[port3];
		motor[port2] = (gerror * gkp * -1) - (der * kd * -1);//set motor power
		motor[port3] = (gerror * gkp * -1) - (der * kd* -1);
		motor[port8] = (gerror * gkp) - (der * kd);
		motor[port9] = (gerror * gkp) - (der * kd);
		der = gerror;
		if(SensorValue[port3]/10 <= gyroval + 2 && SensorValue[port3]/10 >= gyroval - 2)
		{
			wait10Msec(5);
			if(SensorValue[port3]/10 <= gyroval + 2 && SensorValue[port3]/10 >= gyroval - 2)
				checkr = true;


		}
		wait1Msec(5);
	}
	checkr = false;
	motor[port2] = 0;//set motor power
	motor[port3] = 0;
	motor[port8] = 0;
	motor[port9] = 0;
	wait10Msec(30);

}



void drivepid(int targetr, int targetl)
{
	SensorValue[dgtl1] = 0;
	SensorValue[dgtl3] = 0;
	float powerl = 30;
	float powerr = 30;
	float derl = 0;
	float Kpr = 0.3;
	float Kdr = 0.56;
	float Kir = 0.01;
	float Kpl = 0.3;
	float Kdl = 0.56;
	float Kil = 0.01;
	float integralr = 0;
	float integrall = 0;
	float derr = 0;
	float errorr;
	float errorl = 0;
	bool checkr = false;

	while(checkr == false)
	{
		errorr = targetr - SensorValue[dgtl1];
	  errorl = targetl - SensorValue[dgtl3];
		if (integralr < 50 || integralr > -50)
			integralr += errorr;
	  if (integrall < 50 || integrall > -50)
			integrall += errorl;
		powerr = ((Kpr * errorr) + (integralr * Kir)) - (derr * Kdr);
		powerl = ((Kpl * errorl) + (integrall * Kil)) - (derl * Kdl);
		if (powerr > 127)
			powerr = 127;
		if (powerl > 127)
			powerl = 127;
		motor[port2] = powerl;//set motor power
		motor[port3] = powerl;
		motor[port8] = powerr;
		motor[port9] = powerr;
		derr = errorr;
		derl = errorl;
		if(SensorValue[dgtl1] < targetr + 10 && SensorValue[dgtl1] > targetr - 10)
		{
			wait10Msec(1);
			if(SensorValue[dgtl1] < targetr + 10 && SensorValue[dgtl1] > targetr - 10)
				checkr = true;

		}
	}
	checkr = false;
	motor[port2] = 0;//set motor power
	motor[port3] = 0;
	motor[port8] = 0;
	motor[port9] = 0;
	wait10Msec(30);

}
task autonomous()
{

	/*
	**********************************************************************************************************8
	INSTRUCTIONS HERE!!!!!!!!!!!!!!!!!!!!!( for pids);
		mogoliftdown(); makes the mogo lift outake all the way
		mogoliftuo(); makes mogo lift intake all the way
		mogoliftbit(); makes mogolift outake just a bit so that mogo can be launched(used in 20 point zone)

		drivepid(number, number); is used to driveforward !!!!!--> make sure both numbers are the same, otherwise bot wont go straight
		format goes as up there
		ex: drivepid(200, 200); makes the bot go forward 200 ticks and stops at 200 ticks
		you can use negative numbers to backwards
		ex: drivepid(-200, -200);
		makes bot go 200 ticks backwards

		drivepid(number); is used to turn the bot using gyro sensor, IMPORTANT!--> make sure gyro keps nuts are tightened once in a while
		POSITIVE numbers make the bot turn LEFT
		NEGATIVE numbers make the bot turn RIGHT, the gyro is like this
		ex:
		turnpid(45); makes bot turn left 45 degrees
		turnpid(90); makes bot turn 90 degrees left
		turnpid(-45); makes bot turn right 45 degrees
		turnpid(-90); makes bot turn 90 degrees right

		align to same mogo we have done in the past

		*******************************************************************************************
	*/
	SensorValue[dgtl1] = 0;
	SensorValue[dgtl3] = 0;
	mogoliftdown();// mogo lift goes down
	drivepid(1550, 1550);//drive to first mogo
	mogoliftup();//pick up mogo
	drivepid(-1300, -1300);// drive back to just infront of 1 point zone bar
	turnpid(45);//turn 45 degrees like we always have
	drivepid(-350, -350);//go backwards along 10 point zone bar
	turnpid(90);//second turn into 20
  mogoliftbit();// outatakes just a bit to be launched into 20
  drivepid(700, 700);// drive into 20 point zone
  drivepid(-300, -300);//drive out of 20 point zone bar
  turnpid(90);//turn left 90 degrees
  drivepid(-150, -150);//drive back along 10 point zone bar a bit
  turnpid(90);// turn 90 degrees left again facing second mogo
  drivepid(-130, -130);// aligign with bar by backing into it
  mogoliftdown();
  drivepid(700, 700);//drive toward second mogo
  mogoliftup();// pick  up second mogho
  turnpid(180);//turn 180
  drivepid(600, 600);// drive toward 10 point zone bar
 	mogoliftdown();//score mogo
 	drivepid(-800, -800);//drive out
 	mogoliftup();
 	turnpid(90);//turn to face mogo 3
 	mogoliftdown();
 	wait10Msec(10);
 	drivepid(675, 675);
 	mogoliftup();
 	turnpid(-90);
 	drivepid(600, 600);
 	mogoliftdown();
 	drivepid(-200, -200);
 // REMEMBER TO INPUT 2 OF THE SAME NUMBER SEPERATED BY A COMMA IN drivepid(num, num);
 // this code is for 30 point, you have to make the rest*/

}





/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop



     while(true)
		{// DONT CHANGE IT ALL WORKS!!!!!!!
			motor[port2] = vexRT[Ch3];
			motor[port3] = vexRT[Ch3];
			motor[port8] = vexRT[Ch2];
			motor[port9] = vexRT[Ch2];
			motor[port4] = (vexRT[Btn6U]  - vexRT[Btn6D]) *50;
			motor[port7] = (vexRT[Btn6U]  - vexRT[Btn6D]) *50;
			motor[port10] = (vexRT[Btn8L]  - vexRT[Btn8R]) *-120;

		}


}
